import type { BoxConfig } from "./Config";

export const defaultConfig: BoxConfig = {
  name: "firstConfig",
  combinationArraySize: 0,
  combination: "",
  pinA: 2,
  pinB: 1,
  pinX: 3,
  pinY: 4,
  pinL: 5,
  pinR: 12,
  pinZ: 13,
  pinStart: 14,
  pinUp: 15,
  pinDown: 16,
  pinLeft: 17,
  pinRight: 18,
  pinCUp: 21,
  pinCDown: 22,
  pinCLeft: 23,
  pinCRight: 25,
  pinSwitch: 26,
  pinTilt: 27,
  pinDUp: 33,
  pinDDown: 34,
  pinDLeft: 35,
  pinDRight: 36,
  pinLightShield: 32,
  tiltValue: 80,
  x1Value: 42,
  x2Value: 70,
  y1Value: 42,
  y2Value: 70,
  socdMode: 2,
  switchForDirections: true,
  analogShields: false,
  lValue: 100,
  rValue: 100,
};
